#!/bin/bash
# Debian Optimization Program
# Copyright (c) 2025 By Marvin.W

set -eu

# Debian Gnome Configuring:
gsettings set org.gnome.Settings last-panel 'network'
gsettings set org.gnome.system.location enabled false
gsettings set org.gnome.desktop.session idle-delay 0
gsettings set org.gnome.desktop.screensaver lock-delay 0
gsettings set org.gnome.desktop.screensaver lock-enabled false
gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
gsettings set org.gnome.desktop.notifications show-in-lock-screen false
gsettings set org.gnome.desktop.privacy remove-old-trash-files false
gsettings set org.gnome.desktop.privacy remove-old-temp-files true
gsettings set org.gnome.desktop.privacy old-files-age 1
gsettings set org.gnome.desktop.privacy report-technical-problems false
gsettings set org.gnome.desktop.media-handling autorun-never true
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface enable-animations false
gsettings set org.gnome.desktop.datetime automatic-timezone true
gsettings set org.gnome.desktop.wm.preferences button-layout ':minimize,maximize,close'

gsettings set org.gnome.shell favorite-apps "['org.gnome.Nautilus.desktop', 'org.gnome.Terminal.desktop', 'gnome-system-monitor.desktop', 'org.gnome.Extensions.desktop', 'org.gnome.Settings.desktop']"
gsettings set org.gnome.shell enabled-extensions "['dash-to-dock@micxgx.gmail.com', 'drive-menu@gnome-shell-extensions.gcampax.github.com', 'ubuntu-appindicators@ubuntu.com', 'system-monitor@gnome-shell-extensions.gcampax.github.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'ding@rastersoft.com', 'places-menu@gnome-shell-extensions.gcampax.github.com']"
gsettings set org.gnome.shell.extensions.dash-to-dock dash-max-icon-size 50
gsettings set org.gnome.shell.extensions.dash-to-dock custom-theme-shrink true
gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed true
gsettings set org.gnome.shell.extensions.dash-to-dock dock-position 'LEFT'
gsettings set org.gnome.shell.extensions.dash-to-dock autohide false
gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'FOCUS_APPLICATION_WINDOWS'
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'focus-minimize-or-previews'
gsettings set org.gnome.shell.extensions.dash-to-dock show-mounts-network true
gsettings set org.gnome.shell.extensions.user-theme name 'Yaru-dark'

gsettings set org.gnome.gnome-system-monitor show-dependencies true
gsettings set org.gnome.gnome-system-monitor network-total-in-bits true
gsettings set org.gnome.gnome-system-monitor.disksview col-free-visible true
gsettings set org.gnome.gnome-system-monitor.disksview col-free-width 80
gsettings set org.gnome.gnome-system-monitor current-tab 'resources'

gsettings set org.gnome.desktop.background picture-uri-dark ''
gsettings set org.gnome.desktop.background primary-color '#000000'
gsettings set org.gnome.desktop.background secondary-color '#000000'
gsettings set org.gnome.desktop.background color-shading-type 'solid'

gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true
gsettings set org.gtk.gtk4.Settings.FileChooser show-hidden true
gsettings set org.gnome.nautilus.preferences show-hidden-files true
gsettings set org.gnome.nautilus.window-state maximized true
gsettings set org.gnome.nautilus.icon-view default-zoom-level 'medium'

gsettings set org.gnome.TextEditor show-grid true
gsettings set org.gnome.TextEditor highlight-current-line true
gsettings set org.gnome.TextEditor show-map true
gsettings set org.gnome.TextEditor show-line-numbers true
gsettings set org.gnome.TextEditor use-system-font false
gsettings set org.gnome.TextEditor style-scheme 'oblivion'
gsettings set org.gnome.TextEditor custom-font 'Monospace 12'
gsettings set org.gnome.TextEditor wrap-text true
gsettings set org.gnome.TextEditor restore-session true
gsettings set org.gnome.TextEditor right-margin-position 100
gsettings set org.gnome.TextEditor discover-settings true

profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
profile=${profile:1:-1}
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-columns 180
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" default-size-rows 60
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" use-system-font false
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" font 'Monospace 13'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" cursor-blink-mode 'on'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" use-theme-colors false
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" background-color 'rgb(0,0,0)'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" foreground-color 'rgb(208,207,204)'
gsettings set "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile/" scrollback-unlimited true

# Fetch User Name
USER_NAME=($(ls -d /home/*/|cut -d/ -f3))

sudo apt update
sudo apt install -y --no-install-recommends systemd-timesyncd vim expect \
gnome-keyring-pkcs11 im-config fcitx5 fcitx5-chinese-addons fcitx5-config-qt fcitx5-frontend-gtk4 fcitx5-frontend-gtk3 fcitx5-frontend-gtk2 fonts-wqy-microhei fonts-wqy-zenhei libxss1 xdg-utils

# Purge Obsoleted Kernels and Packages:
sudo apt autopurge -y
sudo apt autoremove -y

# Adding Fcitx5 into AutoStart List
sudo cp /usr/share/applications/org.fcitx.Fcitx5.desktop /etc/xdg/autostart/
sudo bash -c 'echo -e "\nexport XMODIFIERS=@im=fcitx\nexport GTK_IM_MODULE=fcitx\nexport QT_IM_MODULE=fcitx" >> /etc/profile'
gsettings set org.gnome.desktop.interface gtk-im-module 'fcitx5'

# Restore Tailored Bash Environment:
rm -f ~/.bashrc
cp -f /etc/skel/.bashrc ~/

# Download and Configurate RealVNC (Firewall rule added and Disable Wayland)
#LatestVer=$(wget -q -O - https://www.realvnc.com/en/connect/download/vnc/linux/ | grep -m 1 -oP "VNC-Server-[0-9].[0-9]{1,2}.[0-9]-Linux-x64.deb")
#sudo apt install -y xfonts-wqy xorg xserver-xephyr
#wget -P $PWD/Downloads https://downloads.realvnc.com/download/file/vnc.files/${LatestVer}
wget -P /tmp https://raw.githubusercontent.com/vmvwv/vnc/main/VNC.deb
sudo apt install /tmp/VNC.deb
sudo apt -y install lightdm
sudo firewall-cmd --zone=public --permanent --add-service=vncserver-x11-serviced
sudo firewall-cmd --reload
sudo vnclicense -add VKUPN-MTHHC-UDHGS-UWD76-6N36A
#sudo ufw allow 5900
#gdmconf="/etc/gdm3/daemon.conf"
#sudo sed -i 's/^#.*WaylandEnable=.*/WaylandEnable=false/' "$gdmconf"
sudo systemctl enable vncserver-x11-serviced.service
sudo systemctl enable vncserver-virtuald.service
#sudo chkconfig --add vncserver-x11-serviced

history -c
