#!/usr/bin/env bash
#Gnome Setup Program
#Copyright (c) 2026 By Marvin.W

set -Eeuo pipefail

apt update
apt full-upgrade -y
apt install -y --no-install-recommends gnome-core gnome-shell \
network-manager-gnome gnome-audio gnome-clocks gnome-keyring gnome-shell-extension-manager gnome-shell-extension-user-theme gnome-shell-extension-system-monitor gnome-shell-extension-drive-menu gnome-shell-extension-places-menu gnome-shell-extension-prefs gnome-shell-extension-dashtodock gnome-shell-extension-appindicator yaru-theme-gnome-shell gnome-shell-extension-kimpanel gnome-shell-extension-desktop-icons-ng

# Purge Obsoleted Packages, Temporary Files:
apt remove -y gnome-contacts cheese gnome-snapshot simple-scan gnome-maps totem totem-common totem-plugins gnome-connections
apt autoremove -y ; apt autoclean -y ; apt autopurge -y

# Repair Gnome Network Missing due to fail to config NetworkManager from ifupdown:
sudo sed -i \
  -e '/^allow-hotplug/s/^/# /' \
  -e '/^iface/s/^/# /' \
  /etc/network/interfaces
